/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import baseclasses.Course;
import baseclasses.DataContainer;
import javax.swing.JOptionPane;
import utilities.NoDataException;

/**
 *
 * @author mkdesign
 */
public class AddCourse extends javax.swing.JFrame {

    DataContainer dataContainer;
    /**
     * Creates new form AddStudent
     */
    public AddCourse(DataContainer dataContainer) {
        this.dataContainer = dataContainer;
        this.setTitle("Add a Course");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCourseTFRoom = new javax.swing.JTextField();
        addCourseTFCourseName = new javax.swing.JTextField();
        addCourseTFID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exitButton1 = new javax.swing.JButton();
        addStudentSubmitButton1 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addCourseTFRoom.setText("12345A");
        addCourseTFRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseTFRoomActionPerformed(evt);
            }
        });

        addCourseTFCourseName.setText("Java Programming");
        addCourseTFCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseTFCourseNameActionPerformed(evt);
            }
        });

        addCourseTFID.setText("90.301");
        addCourseTFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseTFIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Room");

        jLabel2.setText("Course Name");

        jLabel3.setText("Course ID Number");

        exitButton1.setText("Exit");
        exitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButton1MouseClicked(evt);
            }
        });

        addStudentSubmitButton1.setText("Submit");
        addStudentSubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentSubmitButton1ActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCourseTFRoom)
                    .addComponent(addCourseTFCourseName)
                    .addComponent(addCourseTFID, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(addStudentSubmitButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCourseTFRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCourseTFCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCourseTFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentSubmitButton1)
                    .addComponent(exitButton1)
                    .addComponent(clearButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseTFRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseTFRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseTFRoomActionPerformed

    private void addCourseTFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseTFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseTFIDActionPerformed

    private void addCourseTFCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseTFCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseTFCourseNameActionPerformed

    private void exitButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_exitButton1MouseClicked

    private void addStudentSubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentSubmitButton1ActionPerformed
        // Create new course object and retrieve data from form
        Course newCrs = new Course();
        String courseName = this.addCourseTFCourseName.getText();
        // Check course name for empty data and throw NDE
        try {
            if ("".equals(courseName)) {
                throw new NoDataException(courseName);
            }
        }
        catch (NoDataException nde) {
            JOptionPane.showMessageDialog(null, "No data entered for course name");
        }
        String courseIDString = this.addCourseTFID.getText();
        // Check course ID String for empty data and throw NDE
        try {
            if ("".equals(courseIDString)) {
                throw new NoDataException(courseIDString);
            }
        }
        catch (NoDataException nde) {
            JOptionPane.showMessageDialog(null, "No data entered for course ID");
        }        
        String courseRoom = this.addCourseTFRoom.getText();
        // check course room for empty data
        try {
            if("".equals(courseRoom)) {
                throw new NoDataException(courseRoom); 
            }
        }
        catch (NoDataException nde) {
            JOptionPane.showMessageDialog(null, "No data entered for course room");
        }
        // convert string to float, taking into consideration possibility of
        // number exception error. store information.
        try {
            float courseID = Float.valueOf(courseIDString);
            newCrs.setCourseIdNumber(courseID);
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,"Course ID must be a number!");
        }
        // set variables for course
        newCrs.setCourseName(courseName);
        newCrs.setRoom(courseRoom);
        // add to data container
        dataContainer.getListOfCourses().add(newCrs);
    }//GEN-LAST:event_addStudentSubmitButton1ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.addCourseTFCourseName.setText("");
        this.addCourseTFID.setText("");
        this.addCourseTFRoom.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addCourseTFCourseName;
    private javax.swing.JTextField addCourseTFID;
    private javax.swing.JTextField addCourseTFRoom;
    private javax.swing.JButton addStudentSubmitButton1;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
