/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import baseclasses.DataContainer;
import baseclasses.Faculty;
import javax.swing.JOptionPane;
import utilities.FieldFixer;
import utilities.MiscUtils;
import utilities.NoDataException;

/**
 *
 * @author mkdesign
 */
public class AddFaculty extends javax.swing.JFrame {

    DataContainer dataContainer;
    /**
     * Creates new form AddStudent
     */
    public AddFaculty(DataContainer dataContainer) {
        this.dataContainer = dataContainer;
        this.setTitle("Add a Faculty Member");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFacultyTFName = new javax.swing.JTextField();
        addFacultyTFAddress = new javax.swing.JTextField();
        addFacultyTFSSN = new javax.swing.JTextField();
        addFacultyTFDOB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DOH = new javax.swing.JTextField();
        addFacultyTFSalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exitButton1 = new javax.swing.JButton();
        addStudentSubmitButton1 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addFacultyTFName.setText("Firstname Lastname");
        addFacultyTFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyTFNameActionPerformed(evt);
            }
        });

        addFacultyTFAddress.setText("000 sample st");

        addFacultyTFSSN.setText("123456789 - no dashes");
        addFacultyTFSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyTFSSNActionPerformed(evt);
            }
        });

        addFacultyTFDOB.setText("MMDDYYYY");
        addFacultyTFDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyTFDOBActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Address");

        jLabel3.setText("Social Security Number");

        jLabel4.setText("Date of Birth");

        DOH.setText("MMDDYYYY");
        DOH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOHActionPerformed(evt);
            }
        });

        addFacultyTFSalary.setText("jTextField6");

        jLabel5.setText("Date of Hire");

        jLabel6.setText("Salary");

        exitButton1.setText("Exit");
        exitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButton1MouseClicked(evt);
            }
        });

        addStudentSubmitButton1.setText("Submit");
        addStudentSubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentSubmitButton1ActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addFacultyTFSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(DOH)
                    .addComponent(addFacultyTFName)
                    .addComponent(addFacultyTFAddress)
                    .addComponent(addFacultyTFSSN)
                    .addComponent(addFacultyTFDOB))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(addStudentSubmitButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addFacultyTFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFacultyTFAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addFacultyTFSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFacultyTFDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFacultyTFSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentSubmitButton1)
                    .addComponent(exitButton1)
                    .addComponent(clearButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFacultyTFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyTFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFacultyTFNameActionPerformed

    private void addFacultyTFSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyTFSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFacultyTFSSNActionPerformed

    private void DOHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOHActionPerformed

    private void addFacultyTFDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyTFDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFacultyTFDOBActionPerformed

    private void exitButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_exitButton1MouseClicked

    private void addStudentSubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentSubmitButton1ActionPerformed
        // Create a new faculty object and retrieve data from form
        // Store information
        Faculty newFac = new Faculty();
        String name = this.addFacultyTFName.getText();
        // check for NDE and if it passes, set variable to faculty
        try {
            if ("".equals(name)) {
                throw new NoDataException(name);
            }
        }
        catch (NoDataException nde) {
            JOptionPane.showMessageDialog(null,"No data entered for name");
        }
        newFac.setName(name);
        // check for NDE and if it passes, set variable to faculty
        String address = this.addFacultyTFAddress.getText();
        try {
            if ("".equals(address)) {
                throw new NoDataException(name);
            }
        }
        catch (NoDataException nde) {
            JOptionPane.showMessageDialog(null,"No data entered for address");
        }
        newFac.setAddress(address);
        String strSSN = this.addFacultyTFSSN.getText();
        // check validity of SSN then assign
        try {
            if ("".equals(strSSN)) {
                throw new NoDataException(strSSN);
            } 
            else if( strSSN.length() != 9 ) {
                JOptionPane.showMessageDialog(null,"SSN must be 9 digits long. No dashes.");
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for SSN");
        }
        newFac.setSocialSecurityNumber(strSSN);
        String dob = this.addFacultyTFDOB.getText();
        // check validity of DOB then assign
        try {
            if ("".equals(dob)) {
                throw new NoDataException(dob);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for DOB");
        }
        newFac.setDateOfBirth(dob);
        String doh = this.DOH.getText();
        // check validity of DOH then assign
        try {
            if ("".equals(doh)) {
                throw new NoDataException(doh);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for DOH");
        }
        newFac.setDateOfHire(doh);
        String strSalary = this.addFacultyTFSalary.getText();
        // check for NDE
        try {
            if ("".equals(strSalary)) {
                throw new NoDataException(strSalary);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for Salary");
        }
        // use regex to parse string for dollar signs and commas
        strSalary = FieldFixer.moneyFixer(strSalary);
        
        try {
            // note: BigDecimal may be a better option than Double if accuracy
            // is important. for simplicity, will use double.
            double salary = Double.valueOf(strSalary);
            salary = MiscUtils.round(salary, 2);
            newFac.setSalary(salary);
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,"Salary must be a double");
        }
        // add to data container
        dataContainer.getListOfFaculty().add(newFac);                                        
    }//GEN-LAST:event_addStudentSubmitButton1ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.addFacultyTFName.setText("");
        this.addFacultyTFAddress.setText("");
        this.addFacultyTFSSN.setText("");
        this.addFacultyTFDOB.setText("");
        this.DOH.setText("");
        this.addFacultyTFSalary.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOH;
    private javax.swing.JTextField addFacultyTFAddress;
    private javax.swing.JTextField addFacultyTFDOB;
    private javax.swing.JTextField addFacultyTFName;
    private javax.swing.JTextField addFacultyTFSSN;
    private javax.swing.JTextField addFacultyTFSalary;
    private javax.swing.JButton addStudentSubmitButton1;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
