/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import baseclasses.DataContainer;
import baseclasses.Student;
import javax.swing.JOptionPane;
import utilities.NoDataException;

/**
 *
 * @author mkdesign
 */
public class AddStudent extends javax.swing.JFrame {
    DataContainer dataContainer;
    /**
     * Creates new form AddStudent
     */
    public AddStudent(DataContainer dataContainer) {
        this.dataContainer = dataContainer;
        this.setTitle("Add a Student");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addStudentTFName = new javax.swing.JTextField();
        addStudentTFAddress = new javax.swing.JTextField();
        addStudentTFSSN = new javax.swing.JTextField();
        addStudentTFDOB = new javax.swing.JTextField();
        addStudentLabelName = new javax.swing.JLabel();
        addStudentLabelAddress = new javax.swing.JLabel();
        addStudentLabelSSN = new javax.swing.JLabel();
        addStudentLabelDOB = new javax.swing.JLabel();
        addStudentTFGPA = new javax.swing.JTextField();
        addStudentTFDOG = new javax.swing.JTextField();
        addStudentLabelCurrGPA = new javax.swing.JLabel();
        addStudentLabelDofGrad = new javax.swing.JLabel();
        exitButton1 = new javax.swing.JButton();
        addStudentSubmitButton1 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addStudentTFName.setText("<First name Last name>");
        addStudentTFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentTFNameActionPerformed(evt);
            }
        });

        addStudentTFAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentTFAddressActionPerformed(evt);
            }
        });

        addStudentTFSSN.setText("ssn with no dashes");
        addStudentTFSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentTFSSNActionPerformed(evt);
            }
        });

        addStudentTFDOB.setText("MMDDYYYY");
        addStudentTFDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentTFDOBActionPerformed(evt);
            }
        });

        addStudentLabelName.setText("Name");

        addStudentLabelAddress.setText("Address");

        addStudentLabelSSN.setText("Social Security Number");

        addStudentLabelDOB.setText("Date of Birth");

        addStudentTFGPA.setText("0.0");

        addStudentTFDOG.setText("MMDDYYYY");
        addStudentTFDOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentTFDOGActionPerformed(evt);
            }
        });

        addStudentLabelCurrGPA.setText("Current GPA");

        addStudentLabelDofGrad.setText("Date of Graduation");

        exitButton1.setText("Exit");
        exitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButton1MouseClicked(evt);
            }
        });

        addStudentSubmitButton1.setText("Submit");
        addStudentSubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentSubmitButton1ActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addStudentLabelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudentLabelSSN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudentLabelDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudentLabelAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudentLabelCurrGPA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudentLabelDofGrad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStudentTFDOG)
                    .addComponent(addStudentTFGPA)
                    .addComponent(addStudentTFName, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(addStudentTFAddress)
                    .addComponent(addStudentTFSSN)
                    .addComponent(addStudentTFDOB))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(addStudentSubmitButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addStudentTFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addStudentTFAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addStudentTFSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addStudentLabelSSN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addStudentTFDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addStudentLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addStudentLabelAddress)
                        .addGap(33, 33, 33)
                        .addComponent(addStudentLabelDOB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentTFGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudentLabelCurrGPA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentTFDOG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudentLabelDofGrad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentSubmitButton1)
                    .addComponent(exitButton1)
                    .addComponent(clearButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentTFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentTFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentTFNameActionPerformed

    private void addStudentTFAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentTFAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentTFAddressActionPerformed

    private void addStudentTFDOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentTFDOGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentTFDOGActionPerformed

    private void addStudentTFDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentTFDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentTFDOBActionPerformed

    private void addStudentTFSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentTFSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentTFSSNActionPerformed

    private void exitButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exitButton1MouseClicked

    private void addStudentSubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentSubmitButton1ActionPerformed
        // Create a new student object
        Student newStu = new Student();
        // Retrieve and store information from form
        String name = this.addStudentTFName.getText();
        // check for NDE
        try {
            if("".equals(name)) {
                throw new NoDataException(name);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for name");
        }
        newStu.setName(name);
        
        String address = this.addStudentTFAddress.getText();
        // check for NDE
        try {
            if("".equals(address)) {
                throw new NoDataException(address);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for address");
        }
        newStu.setAddress(address);
        
        // process SSN
        String strSSN = this.addStudentTFSSN.getText();
        // check for NDE
        try {
            if("".equals(strSSN)) {
                throw new NoDataException(strSSN);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for SSN");
        }
        // check SSN length
        if ( strSSN.length() != 9 ) {
            JOptionPane.showMessageDialog(null, "SSN must be 9 digits long. No dashes.");
        }
        newStu.setSocialSecurityNumber(strSSN);
        
        String strGPA = this.addStudentTFGPA.getText();
        // check for NDE
        try {
            if ("".equals(strGPA)) {
                throw new NoDataException(strGPA);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"NO data entered for GPA");
        }
        // parse GPA string, convert to float and catch exception
        try {
            float GPA = Float.valueOf(strGPA);
            newStu.setCurrentGPA(GPA);
        } 
        catch ( NumberFormatException nfe ) {
            JOptionPane.showMessageDialog(null,"GPA must be numeric.");
        }
        String DOB = this.addStudentTFDOB.getText();
        // check for NDE
        try {
            if ("".equals(DOB)) {
                throw new NoDataException(DOB);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for DOB");
        }
        newStu.setDateOfBirth(DOB);
        
        String DOG = this.addStudentTFDOG.getText();
        try {
            if ("".equals(DOG)) {
                throw new NoDataException(DOG);
            }
        }
        catch ( NoDataException nde ) {
            JOptionPane.showMessageDialog(null,"No data entered for DOG");
        }
        newStu.setDateOfGraduation(DOG);
        // add to container
        dataContainer.getListOfStudents().add(newStu);
    }//GEN-LAST:event_addStudentSubmitButton1ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.addStudentTFAddress.setText("");
        this.addStudentTFDOB.setText("");
        this.addStudentTFDOG.setText("");
        this.addStudentTFGPA.setText("");
        this.addStudentTFName.setText("");
        this.addStudentTFSSN.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addStudentLabelAddress;
    private javax.swing.JLabel addStudentLabelCurrGPA;
    private javax.swing.JLabel addStudentLabelDOB;
    private javax.swing.JLabel addStudentLabelDofGrad;
    private javax.swing.JLabel addStudentLabelName;
    private javax.swing.JLabel addStudentLabelSSN;
    private javax.swing.JButton addStudentSubmitButton1;
    private javax.swing.JTextField addStudentTFAddress;
    private javax.swing.JTextField addStudentTFDOB;
    private javax.swing.JTextField addStudentTFDOG;
    private javax.swing.JTextField addStudentTFGPA;
    private javax.swing.JTextField addStudentTFName;
    private javax.swing.JTextField addStudentTFSSN;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton1;
    // End of variables declaration//GEN-END:variables
}
